#
# This software may be modified and distributed under the terms
# of the MIT license.  See the LICENSE file for details.

name: CI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Python ${{ matrix.python }}
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python: ['3.10', '3.11', '3.12']
      fail-fast: false

    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install --upgrade pip setuptools tox

      - name: Run tests
        run: tox -e py
